2018-03-13 20:00:34,416 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 47]
2018-03-13 23:24:37,071 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 47]
2018-03-13 23:29:43,840 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 47]
2018-03-13 23:33:27,993 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 47]
2018-03-13 23:34:14,333 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 47]
2018-03-20 00:17:19,760 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-20 00:25:48,058 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-21 23:34:29,180 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-22 01:31:11,664 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-22 01:35:15,361 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-22 01:36:11,574 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-22 01:38:09,658 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-22 01:39:17,174 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-22 01:40:14,786 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-22 01:41:39,205 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-22 01:43:28,439 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-22 01:46:40,150 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-22 01:47:34,604 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-22 01:52:07,482 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-22 22:11:43,182 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 22:54:50,378 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 23:12:20,499 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 23:14:04,949 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 23:18:27,604 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 23:20:32,122 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 23:21:15,495 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 23:23:04,503 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 23:26:01,724 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 23:27:42,839 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 23:28:09,975 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 23:30:26,662 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 23:31:32,692 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 23:32:22,108 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 23:33:30,467 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 23:34:22,170 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 23:35:15,519 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 23:36:57,104 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 23:37:26,306 ERROR: Exception on /index [GET] [in /home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py: 1560]
Traceback (most recent call last):
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ari/Documents/LastChance/microblog/app/routes.py", line 81, in index
    posts = posts.items, next_url=next_url, prev_url=prev_url)
AttributeError: 'list' object has no attribute 'items'
2018-03-25 23:46:02,578 ERROR: Exception on /index [GET] [in /home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py: 1560]
Traceback (most recent call last):
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ari/Documents/LastChance/microblog/app/routes.py", line 81, in index
    posts = posts.items, next_url=next_url, prev_url=prev_url)
AttributeError: 'list' object has no attribute 'items'
2018-03-25 23:46:16,582 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 23:47:40,396 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-03-25 23:47:46,041 ERROR: Exception on /index [GET] [in /home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py: 1560]
Traceback (most recent call last):
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ari/Documents/LastChance/microblog/app/routes.py", line 81, in index
    posts = posts.items, next_url=next_url, prev_url=prev_url)
AttributeError: 'list' object has no attribute 'items'
